name: list_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.0
  sqflite: ^2.3.2
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^3.0.0
=======
  flutter_lints: ^2.0.0
>>>>>>> 1a6b368e9373e2a9d8e1315dfa992cc58896dca3

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
  - assets/images/
=======
    - assets/images/
    - assets/fonts/
>>>>>>> 1a6b368e9373e2a9d8e1315dfa992cc58896dca3
  fonts:
    - family: Nunito
      fonts:
<<<<<<< HEAD
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
          weight: 600
=======
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
>>>>>>> 1a6b368e9373e2a9d8e1315dfa992cc58896dca3
